Repository Pawtang/roguelike, pull requests merged in 2019-04, with the labels that each got.

#24 Maze generation
  README.md
  css/map.css
  index.html
  js/events.js
  js/index.js
  js/maze.js
  js/shop.js
Labels: feature, review ready, v1.0

#27 Map builder
  css/map.css
  images/tiles/floor-1.png
  images/tiles/floor.png
  images/tiles/wall-1.png
  images/tiles/wall.png
  index.html
  js/index.js
  js/maze.js
Labels: feature, v1.0

#30 Game over implementation
  index.html
  js/index.js
  js/player.js
Labels: bug, feature, refactor, review ready, v1.0
